server:
  port: 8080

spring:
  kafka:
    consumer:
      bootstrap-servers: 192.168.1.53:9092, 192.168.1.53:9093
      group-id: group-id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

    producer:
      bootstrap-servers: 192.168.1.53:9092, 192.168.1.53:9093
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer